export interface usersSale{
    userId: string,
    fullName: string,
    rol: string,
    job: string
}

export interface User {
    uid?: string;
    token?: string;
    currentToken?: string;
    name?: string;
    email?: string;
    rol?: string;
  }

export const Days=[
    {id:1, day: "1"},
    {id:2, day: "2"},
    {id:3, day: "3"},
    {id:4, day: "4"},
    {id:5, day: "5"},
    {id:6, day: "6"},
    {id:7, day: "7"}
]


export interface ClientSAE{
    CLAVE:string,
    STATUS:string,
    NOMBRE:string,
    RFC:string,
    CALLE:string,
    NUMINT:string,
    NUMEXT:string,
    CRUZAMIENTOS:string,
    CRUZAMIENTOS2:string,
    COLONIA:string,
    CODIGO:string,
    LOCALIDAD:string,
    MUNICIPIO:string,
    ESTADO:string,
    PAIS:string,
    NACIONALIDAD:string,
    REFERDIR:string,
    TELEFONO:string,
    CLASIFIC:string,
    FAX:string,
    PAG_WEB:string,
    CURP:string,
    CVE_ZONA:string,
    IMPRIR:string,
    MAIL:string,
    NIVELSEC:string,
    ENVIOSILEN:string,
    EMAILPRED:string,
    DIAREV:string,
    DIAPAGO:string,
    CON_CREDITO:string,
    DIASCRED:number,
    LIMCRED:number,
    SALDO:number,
    LISTA_PREC:number,
    CVE_BITA:number,
    ULT_PAGOD:string,
    ULT_PAGOM:number,
    ULT_PAGOF:number,
    DESCUENTO:number,
    ULT_VENTAD:string,
    ULT_COMPM:number,
    FCH_ULTCOM:string,
    VENTAS:number,
    CVE_VEND:string,
    CVE_OBS:number,
    TIPO_EMPRESA:string,
    MATRIZ:string,
    PROSPECTO:string,
    CALLE_ENVIO:string,
    NUMINT_ENVIO:string,
    NUMEXT_ENVIO:string,
    CRUZAMIENTOS_ENVIO:string,
    CRUZAMIENTOS_ENVIO2:string,
    COLONIA_ENVIO:string,
    LOCALIDAD_ENVIO:string,
    MUNICIPIO_ENVIO:string,
    ESTADO_ENVIO:string,
    PAIS_ENVIO:string,
    CODIGO_ENVIO:string,
    CVE_ZONA_ENVIO:string,
    REFERENCIA_ENVIO:string,
    CUENTA_CONTABLE:string,
    ADDENDAF:string,
    ADDENDAD:string,
    NAMESPACE:string,
    METODODEPAGO:string,
    NUMCTAPAGO:string,
    MODELO:string,
    DES_IMPU1:string,
    DES_IMPU2:string,
    DES_IMPU3:string,
    DES_IMPU4:string,
    DES_PER:string,
    LAT_GENERAL:number,
    LON_GENERAL:number,
    LAT_ENVIO:number,
    LON_ENVIO:number,
    UUID:string,
    VERSION_SINC:string,
    USO_CFDI:string,
    CVE_PAIS_SAT:string,
    NUMIDREGFISCAL:string,
    FORMADEPAGOSAT:string,
    ADDENDAG:string,
    ADDENDAE:string
}